# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Comp541Projects/Lab8/Lab8New/Lab8New.cache/wt [current_project]
set_property parent.project_path C:/Comp541Projects/Lab8/Lab8New/Lab8New.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Comp541Projects/Lab8/Lab8New/Lab8New.srcs/sources_1/imports/sources_1/imports/new/debouncer.sv
  C:/Comp541Projects/Lab8/Lab8New/Lab8New.srcs/sources_1/imports/sources_1/imports/new/fsm.sv
  C:/Comp541Projects/Lab8/Lab8New/Lab8New.srcs/sources_1/imports/sources_1/new/ram.sv
  C:/Comp541Projects/Lab8/Lab8New/Lab8New.srcs/sources_1/imports/sources_1/new/hexto7seg.sv
}
read_verilog -library xil_defaultlib {
  C:/Comp541Projects/Lab8/Lab8New/Lab8New.srcs/sources_1/imports/sources_1/new/comb.v
  C:/Comp541Projects/Lab8/Lab8New/Lab8New.srcs/sources_1/imports/sources_1/new/memdemo.v
}
read_xdc C:/Comp541Projects/Lab8/Lab8New/Lab8New.srcs/constrs_1/imports/new/memdemo.xdc
set_property used_in_implementation false [get_files C:/Comp541Projects/Lab8/Lab8New/Lab8New.srcs/constrs_1/imports/new/memdemo.xdc]

catch { write_hwdef -file memdemo.hwdef }
synth_design -top memdemo -part xc7a100tcsg324-1
write_checkpoint -noxdef memdemo.dcp
catch { report_utilization -file memdemo_utilization_synth.rpt -pb memdemo_utilization_synth.pb }
