# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Libraries/Documents/GitHub/Lab6/Lab6.cache/wt [current_project]
set_property parent.project_path E:/Libraries/Documents/GitHub/Lab6/Lab6.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv {
  E:/Libraries/Documents/GitHub/Lab6/Lab6.srcs/sources_1/new/fsm.sv
  E:/Libraries/Documents/GitHub/Lab6/Lab6.srcs/sources_1/new/counter.sv
  E:/Libraries/Documents/GitHub/Lab6/Lab6.srcs/sources_1/new/debouncer.sv
  E:/Libraries/Documents/GitHub/Lab6/Lab6.srcs/sources_1/new/display4digit.sv
  E:/Libraries/Documents/GitHub/Lab6/Lab6.srcs/sources_1/new/stopwatch.sv
}
read_verilog -library xil_defaultlib E:/Libraries/Documents/GitHub/Lab6/Lab6.srcs/sources_1/imports/Downloads/hexto7seg.v
read_xdc E:/Libraries/Documents/GitHub/Lab6/Lab6.srcs/constrs_1/new/stopwatch.xdc
set_property used_in_implementation false [get_files E:/Libraries/Documents/GitHub/Lab6/Lab6.srcs/constrs_1/new/stopwatch.xdc]

catch { write_hwdef -file stopwatch.hwdef }
synth_design -top stopwatch -part xc7a100tcsg324-1
write_checkpoint -noxdef stopwatch.dcp
catch { report_utilization -file stopwatch_utilization_synth.rpt -pb stopwatch_utilization_synth.pb }
