# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Comp541Projects/Lab10/Lab10.cache/wt [current_project]
set_property parent.project_path C:/Comp541Projects/Lab10/Lab10.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Comp541Projects/Lab10/Lab10.srcs/sources_1/imports/new/register_file.sv
  C:/Comp541Projects/Lab10/Lab10.srcs/sources_1/imports/new/datapath.v
  C:/Comp541Projects/Lab10/Lab10.srcs/sources_1/new/controller.sv
  C:/Comp541Projects/Lab10/Lab10.srcs/sources_1/new/imem.sv
  C:/Comp541Projects/Lab10/Lab10.srcs/sources_1/new/dmem.sv
  C:/Comp541Projects/Lab10/Lab10.srcs/sources_1/new/mips.sv
  C:/Comp541Projects/Lab10/Lab10.srcs/sources_1/new/top.sv
}
read_verilog -library xil_defaultlib {
  C:/Comp541Projects/Lab10/Lab10.srcs/sources_1/imports/sources_1/imports/new/fulladder.v
  C:/Comp541Projects/Lab10/Lab10.srcs/sources_1/imports/sources_1/new/adder.v
  C:/Comp541Projects/Lab10/Lab10.srcs/sources_1/imports/sources_1/imports/Lab_3/shifter.v
  C:/Comp541Projects/Lab10/Lab10.srcs/sources_1/imports/sources_1/imports/Lab_3/logical.v
  C:/Comp541Projects/Lab10/Lab10.srcs/sources_1/imports/sources_1/imports/Lab_3/comparator.v
  C:/Comp541Projects/Lab10/Lab10.srcs/sources_1/imports/sources_1/new/addsub.v
  C:/Comp541Projects/Lab10/Lab10.srcs/sources_1/imports/sources_1/imports/Lab_3/ALU.v
}
catch { write_hwdef -file top.hwdef }
synth_design -top top -part xc7a100tcsg324-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
