# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Libraries/Documents/GitHub/Lab7/Lab7.cache/wt [current_project]
set_property parent.project_path E:/Libraries/Documents/GitHub/Lab7/Lab7.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv {
  E:/Libraries/Documents/GitHub/Lab7/Lab7.srcs/sources_1/new/xycounter.sv
  E:/Libraries/Documents/GitHub/Lab7/Lab7.srcs/sources_1/new/display640x480.sv
  E:/Libraries/Documents/GitHub/Lab7/Lab7.srcs/sources_1/new/vgatimer.sv
  E:/Libraries/Documents/GitHub/Lab7/Lab7.srcs/sources_1/new/vgadisplaydriver.sv
}
read_xdc E:/Libraries/Documents/GitHub/Lab7/Lab7.srcs/constrs_1/new/vgadisplaydriver.xdc
set_property used_in_implementation false [get_files E:/Libraries/Documents/GitHub/Lab7/Lab7.srcs/constrs_1/new/vgadisplaydriver.xdc]

catch { write_hwdef -file vgadisplaydriver.hwdef }
synth_design -top vgadisplaydriver -part xc7a100tcsg324-1
write_checkpoint -noxdef vgadisplaydriver.dcp
catch { report_utilization -file vgadisplaydriver_utilization_synth.rpt -pb vgadisplaydriver_utilization_synth.pb }
