# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Libraries/Documents/GitHub/Comp541Lab3/Lab3/Lab3.cache/wt [current_project]
set_property parent.project_path E:/Libraries/Documents/GitHub/Comp541Lab3/Lab3/Lab3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  E:/Libraries/Documents/GitHub/Comp541Lab3/Lab3/Lab3.srcs/sources_1/imports/new/fulladder.v
  E:/Libraries/Documents/GitHub/Comp541Lab3/Lab3/Lab3.srcs/sources_1/new/adder.v
  E:/Libraries/Documents/GitHub/Comp541Lab3/Lab3/Lab3.srcs/sources_1/new/comparator.v
  E:/Libraries/Documents/GitHub/Comp541Lab3/Lab3/Lab3.srcs/sources_1/new/shifter.v
  E:/Libraries/Documents/GitHub/Comp541Lab3/Lab3/Lab3.srcs/sources_1/new/logical.v
  E:/Libraries/Documents/GitHub/Comp541Lab3/Lab3/Lab3.srcs/sources_1/new/addsub.v
  E:/Libraries/Documents/GitHub/Comp541Lab3/Lab3/Lab3.srcs/sources_1/new/ALU.v
}
catch { write_hwdef -file ALU.hwdef }
synth_design -top ALU -part xc7a100tcsg324-1
write_checkpoint -noxdef ALU.dcp
catch { report_utilization -file ALU_utilization_synth.rpt -pb ALU_utilization_synth.pb }
